### ISSUE TITLE
Local Option Map

### ISSUE THREAD

**Issue by anthonysgevans** [javiercf/react-scribe#4]
Hi All, 

First, thanks for porting the scribe-editor to react - it's great.

We'd like to create our own plugins for the editor but are stuck for a way to define our own plugins without editing `optionMap.js` in the react-scribe package.  

Would it be a good idea to pass option objects as parameters to the ScribeEditor at runtime, or specifiy alternative locations of objectMap definitions that could exist outside of the package?

Regards, 

Anthony.

**Comment by javiercf** [comment]
Hi Anthony,

I usually define custom plugins and pass it in as a prop to the editor, here is an example

```
const scribeOptions = [
		'small',
		{
			command: 'mediaPrompt',
			display: 'fa-icon fa-picture-o',
			action: props.WYSIWGYModal()
		},
		{
			command: 'iframe',
			display: 'fa fa-video-camera',
			action: scribe => {
				const frameCmd = new scribe.api.Command('insertHTML');

				frameCmd.execute = () => {
					scribe.api.Command.prototype.execute.call(frameCmd,
						`<div class="videoContainer"><div class="video">${window.prompt('Pegue el código del Iframe')}</div></div>`
					)
				}

				scribe.commands.iframe = frameCmd;
			}
		},
		'blockquote', 'code', 'h3', 'linkPrompt', 'unlink', 'ol', 'ul'
	];
```
and then you can do 
```
<ScribeEditor config={scribeOptions} />
```

**Comment by anthonysgevans** [comment]
Hi Javier,

Great, that's exactly what I was hoping for!

Thanks for the quick response!
